version: '3.7'

services:

    db:
        image: postgres:latest
        hostname: database
        user: postgres
        ports:
            - 5432:5432
        volumes:
            - ${HOME}/postgresDB/:/var/lib/postgresql/data
        networks:
            - default
        # environment:
        #     - POSTGRES_USER=postgres
        #     - POSTGRES_PASSWORD=1234
        
    adminer:
        image: dpage/pgadmin4
        ports:
            - 80:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=sireanu.roland@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=1234

    redis-server:
        image: redis:latest
        ports:
            - 6379:6379

    # update-prices:
    #     build: ./UpdatePrices
    #     networks:
    #         - default

networks:
  internalnetwork:
    driver: bridge
