version: '3.7'

services:

    db:
        image: postgres:13
        restart: always
        ports:
                - 127.0.0.1:5432:5432
        volumes:
                - postgres-vol:/var/lib/postgresql/data
        networks:
            - internalnetwork
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=trader 
    
    webserver:  
        build:
                dockerfile: ./DockerFiles/DockerNginx/Dockerfile
                context: .
        restart: always
        ports: 
           - 80:80
        networks:
           - internalnetwork  
        
    adminer:
        image: dpage/pgadmin4
        ports:
            - 81:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=sireanu.roland@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=1234
        networks:
            - internalnetwork
    
    # rqworker:
    #     build: ./RqWorker
    #     networks: 
    #         - internalnetwork

    # rqscheduler:
    #     build: ./RqScheduler
    #     networks:
    #         - internalnetwork

    redis-server:
        image: redis:latest
        networks:
            - internalnetwork
        ports:
                - 127.0.0.1:6379:6379

    backend:
        build:
                context: .
                dockerfile: ./DockerFiles/DockerFlask/Dockerfile
        networks:
            - internalnetwork
        ports:
                - 127.0.0.1:5000:5000
        volumes:
            - ./application:/application
        depends_on:
            - redis-server
            - db
        environment:
            - DATABASE_HOST=db
            - USER_EMAIL=${UEMAIL}
            - PASSWORD_EMAIL=${PEMAIL}
                        

    # update-prices:
    #     build: ./UpdatePrices
    #     networks:
    #         - default
    #mail:
    #image: bytemark/smtp
    #restart: always

networks:
  internalnetwork:
    driver: bridge

volumes:
  postgres-vol:
