version: '3.1'

services:

    db:
        image: postgres:latest
        user: postgres
        ports:
            - 5432:5432
        volumes:
            - ${HOME}/postgresDB/:/var/lib/postgresql/data
        # environment:
        #     - POSTGRES_USER=postgres
        #     - POSTGRES_PASSWORD=1234
        
    adminer:
        image: dpage/pgadmin4
        ports:
            - 80:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=sireanu.roland@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=1234

