version: '3.7'

services:

    db:
        image: postgres:13
        restart: always
        ports:
            - 5432:5432
        volumes:
                - postgres-vol:/var/lib/postgresql/data
        networks:
            - internalnetwork
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=trader 
        
        
    adminer:
        image: dpage/pgadmin4
        ports:
            - 80:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=sireanu.roland@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=1234
        networks:
            - internalnetwork
    
    # rqworker:
    #     build: ./RqWorker
    #     networks: 
    #         - internalnetwork

    # rqscheduler:
    #     build: ./RqScheduler
    #     networks:
    #         - internalnetwork

    redis-server:
        image: redis:latest
        networks:
            - internalnetwork
        ports:
            - 6379:6379

    backend:
        build: .
        networks:
            - internalnetwork
        ports:
            - 5000:5000
        volumes:
            - ./application:/application
        depends_on:
            - redis-server
            - db
        environment:
            - DATABASE_HOST=db
                        

    # update-prices:
    #     build: ./UpdatePrices
    #     networks:
    #         - default

networks:
  internalnetwork:
    driver: bridge

volumes:
  postgres-vol:
