version: '3.7'

services:

    db:
        image: postgres:latest
        hostname: database
        user: postgres
        ports:
            - 5432:5432
        volumes:
            - ${HOME}/postgresDB/:/var/lib/postgresql/data
        networks:
            - internalnetwork
        # environment:
        #     - POSTGRES_USER=postgres
        #     - POSTGRES_PASSWORD=1234
        
    adminer:
        image: dpage/pgadmin4
        ports:
            - 80:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=sireanu.roland@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=1234
        networks:
            - internalnetwork
    
    # rqworker:
    #     build: ./RqWorker
    #     networks: 
    #         - internalnetwork

    # rqscheduler:
    #     build: ./RqScheduler
    #     networks:
    #         - internalnetwork

    redis-server:
        image: redis:latest
        networks:
            - internalnetwork
        ports:
            - 6379:6379

    backend:
        build: .
        networks:
            - internalnetwork
        ports:
            - 8001:5000
        volumes:
            - ./application:/application
        depends_on:
            - redis-server
            - db

    # update-prices:
    #     build: ./UpdatePrices
    #     networks:
    #         - default

networks:
  internalnetwork:
    driver: bridge
