"""empty message

Revision ID: 10bf756ca9d1
Revises: c1e47bf29ad7
Create Date: 2021-04-05 23:03:55.363930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10bf756ca9d1'
down_revision = 'c1e47bf29ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices_model', sa.Column('bitcoin', sa.Float(), nullable=True))
    op.add_column('prices_model', sa.Column('cardano', sa.Float(), nullable=True))
    op.add_column('prices_model', sa.Column('ethereum', sa.Float(), nullable=True))
    op.add_column('prices_model', sa.Column('monero', sa.Float(), nullable=True))
    op.add_column('prices_model', sa.Column('ripple', sa.Float(), nullable=True))
    op.drop_column('prices_model', 'ada')
    op.drop_column('prices_model', 'eth')
    op.drop_column('prices_model', 'xrp')
    op.drop_column('prices_model', 'xmr')
    op.drop_column('prices_model', 'btc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices_model', sa.Column('btc', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('prices_model', sa.Column('xmr', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('prices_model', sa.Column('xrp', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('prices_model', sa.Column('eth', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('prices_model', sa.Column('ada', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('prices_model', 'ripple')
    op.drop_column('prices_model', 'monero')
    op.drop_column('prices_model', 'ethereum')
    op.drop_column('prices_model', 'cardano')
    op.drop_column('prices_model', 'bitcoin')
    # ### end Alembic commands ###
