"""empty message

Revision ID: c1e47bf29ad7
Revises: 
Create Date: 2021-04-04 22:30:57.781255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e47bf29ad7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('btc', sa.Float(), nullable=True),
    sa.Column('eth', sa.Float(), nullable=True),
    sa.Column('ada', sa.Float(), nullable=True),
    sa.Column('xrp', sa.Float(), nullable=True),
    sa.Column('xmr', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices_model')
    # ### end Alembic commands ###
